theme: jekyll-theme-midnight

collections:
  docs:
    output: true
    permalink: /docs/:path/

# Если хотите включить файлы из корня репозитория
include:
  - "*.md"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.gif"
  - "*.js-concepts/*"

# Исключите ненужные файлы
exclude:
  - .git
  - .github
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# Настройка отображения файлов
defaults:
  - scope:
      path: "" # Все файлы
    values:
      layout: default